newsite/urls.py
from django.conf.urls import url

from .views import index

app_name='newsite'
urlpatterns = [
    url(r'^$', index, name='index'),
    
]

story8/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include('newsite.urls', namespace='status')),
    url(r'^$', RedirectView.as_view(url='/status/')),
]

newsite/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class Status(models.Model):
    status = models.CharField(max_length=300,
                              validators=[MaxLengthValidator(300)])
    created_at = models.DateTimeField(auto_now_add=True)

newsite/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse



def index(request):
    html = 'index.html'
    return render(request, html)

newsite/templates/index.html
﻿﻿﻿{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>Yaumi Alfadha</title>
<link href="http://fonts.googleapis.com/css?family=Raleway:700,300" rel="stylesheet"
        type="text/css">

</head>
{% block content %}
<body onload="myFunction2()" style="margin:0";>

<div class="se-pre-con" id='loader'></div>
<div class="wrapper" id = "coba">



    <div class="dropdown">
        <button class="dropbtn">Ganti Tema</button>
        <div class="dropdown-content">
          <a onclick="myFunction()">Biru</a>
          <a onclick="myFunction1()">Coklat</a>
        </div>
      </div> 
  
<section>
  <div class="container" id = 'container'>
    
    <div class="docs-content">
      <h2 class="entry-title"> Profile</h2>
    <div class = "biodata">  
    <img id="gambar" src="{% static "assets/img/yaumi.jpg" %}" alt="My image">
    <h3>Yaumi Alfadha<br>Jakarta, 28-03-1999</h3>
  </div>
  
  <button class="accordion">Pengalaman organisasi</button>
  <div class="panel">
    <ul>
      <div class='fuki' style='display:flex'>
        <li>FUKI </li>
        <img id="fuki" src="{% static "assets/img/fuki.jpg" %}">
      </div>
      <li>Compfest</li>
    </ul>
  </div>
  
  <button class="accordion">Aktifitas</button>
  <div class="panel">
    <ul>
      <li>Universitas Indonesia</li>
      <li>SMAN 38 Jakarta</li>
    </ul>
  </div>
  
  <button class="accordion">Prestasi</button>
  <div class="panel">
    <li>Masuk Fasilkom</li>
  </div>    
  
      
</section>
</div>
</body>
<script>
    function myFunction() {
        document.body.style.backgroundColor = "#26abe2";
        
    }
    function myFunction1() {
        document.body.style.backgroundColor = "brown";
        
    }
    var myVar;

    function myFunction2() {
      myVar = setTimeout(showPage, 3000);
    }
    function showPage() {
      document.getElementById("loader").style.display = "none";
      document.getElementById("coba").style.display = "block";
    }
    </script>

<script src="{% static "assets/js/accord.js" %}"></script> 
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&skin=sunburst"></script>


{% endblock content %}
</html>

newsite/templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="landing page">
        <meta name="author" content="Yaumi Alfadha - 1706023013">

        <title>
            {% block title %}
                Yaumi Alfadha - Index
            {% endblock title %}
        </title>

        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'assets\css\prettify.css' %}"> -->
        <link rel="stylesheet" type="text/css" href="{% static 'story8.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Bitter|Chivo|Montserrat" rel="stylesheet">

    </head>

    <body>
        <header>
            {% include 'layout/header.html' %}
        </header>
        <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock content %}
        </content>

        <footer>
            {% include 'layout/footer.html' %}
        </footer>
<!-- 
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
    </body>
</html>

newsite/templates/layout/footer.html
<!DOCTYPE html>
<html lang="en">
        <footer>
                <div class="">
                  <p>Yaumi Alfadha|FASILKOM UI</p>
                </div>
        </footer>
</html>

newsite/templates/layout/header.html
<!-- <!DOCTYPE html>
<html lang="en">
    <nav class="navbar navbar-expand-lg main-navbar">
        <a class="navbar-brand navbar-button" href="{% url 'status:index' %}">Home</a>
        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</html> -->